---
abstract: 'handle JSON like {"a":1, "a":2}'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: '0.61'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Moose::Meta::Class::__ANON__::SERIAL::8 version , CPAN::Meta::Converter version 2.140640'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JSON-MultiValueOrdered
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  JSON::MultiValueOrdered:
    file: lib/JSON/MultiValueOrdered.pm
    version: '0.005'
  JSON::Tiny::Subclassable:
    file: lib/JSON/Tiny/Subclassable.pm
    version: '0.005'
  Tie::Hash::MultiValueOrdered:
    file: lib/Tie/Hash/MultiValueOrdered.pm
    version: '0.005'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/JSON-MultiValueOrdered/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=JSON-MultiValueOrdered
  homepage: https://metacpan.org/release/JSON-MultiValueOrdered
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-json-multivalueordered.git
version: '0.005'
x_contributors:
  - 'David J. Oswald (DAVIDO) <davido@cpan.org>'
